### ISSUE TITLE
开发个小米电视的？

### ISSUE THREAD

**Issue by zhongyingfang** [wukongdaily/tvhelper-docker#1]
小米电视每次安装youtube之类的都要重置出厂设置，找了好久都没有找到能显示4k选项的youtube，能不能集成一个脚本，一键安装google套件和youtube(带4K选项的)？

**Comment by niko8868** [comment]
可以用第三方youtube，https://smarttubeapp.github.io/，无需谷歌框架

**Comment by zhongyingfang** [comment]
> 可以用第三方youtube，无需谷歌框架，https://smarttubeapp.github.io/

这个试过了，一样没有4K选项

**Comment by zhongyingfang** [comment]
> 目前脚本中已经集成了fire tv版本的youtube ，已经有4K的选项了。

是菜单里sony电视里的吗？我安装了还是没有，小米电视是不是没希望了
![Uploading 微信图片_20240306084254.jpg…]()

**Comment by wukongdaily** [comment]
那可能就是你的小米电视 不太符合油管官方对于4K设备的要求吧。
