### ISSUE TITLE
一点小想法

### ISSUE THREAD

**Issue by chinesepy** [wukongdaily/tvhelper-docker#10]
首先感谢开发这个折腾电视盒子小工具并写了尽可能详细的教程方便小白！
以下是一点小小的想法：
1.向TV端输入文字过于麻烦了，可以考虑去掉。大部分场景情况用夏杰语音或者类似的可以手机跨屏输入的输入法可以解决。
2.助手的功能定位如果是用完就关闭的一次性工具的话，似乎没必要开放任何端口，直接使用各种docker管理面板内置的命令行即可。用户把弱口令+固定端口的docker部署在软路由上很容易引起安全问题。
3.助手的功能定位如果是长期运行的服务的话，希望后续添加更多服务性质的功能：比如可以方便管理IPTV直播源的http服务。

**Comment by wukongdaily** [comment]
挺好的思考。有些建议，我采纳了
1、去掉了tv输入文字的功能，这个受限于adb，adb本身能实现文字 字符非常有限，先去掉了
2、新增修改容器SSH密码功能。 容器内22端口虽然开放，但用户可以不对外映射，也就是映射到主机这个步骤不是必须的。用户想用就映射，不想用就不映射了，2299 也不是固定的，随便写，写什么都行。考虑到安全意识问题，新增了 修改密码功能，对于安全有需求的，算是一个提醒，他们会自行修改为强密码。因为有人确实需要使用ssh客户端连接容器，所以就不去掉了。
![CasaOS 2024-03-13 15-40-25](https://github.com/wukongdaily/tvhelper-docker/assets/143675923/71427c76-d2e7-44b7-b0b8-48fd8790026d)
