### ISSUE TITLE
mytvsuper问题

### ISSUE THREAD

**Issue by jjyjul** [wukongdaily/tvhelper-docker#12]
大圣你好，感谢你开发盒子助手,里面有里面有个mytvsuper 我成功装到新买的小米电视上（75s pro）可以进到首页（还可以观看 app里面的广告）但一进正片就显示你的网络已断开。路由全局也一样。而索尼电视就正常（索尼安装的是我自已下的 zip包安装）小米电视不能安装zip xapk apk+等包。我现在不清楚是盒子助手内面的 mytvsuper有问题还是小米电视有限制 (小米电视装助手那个youtueb国正常观看的还支持4k hdr) 附上在谷歌市场下的app内容

**Comment by jjyjul** [comment]
![1710732900203](https://github.com/wukongdaily/tvhelper-docker/assets/56083835/d3d8b9f6-5b9b-459a-9c1d-ec9a6fb236da)

**Comment by wukongdaily** [comment]
这个问题应该是myTvsuper 的兼容适配问题吧，和安装包关系不大。因为它能正常安装，说明不是安装问题。不同的包最多是（安卓）语言数量不同。我这边为了测试还特意注册了一个myTVsuper的账号。
然后使用国内的【小米盒子 4S MAX】，目前是可以播放的。这个小米盒子应该是android 9.0的。4+64G的。
如图所示：
![mytvsuper1](https://github.com/wukongdaily/tvhelper-docker/assets/143675923/048435ef-b10d-4fee-9c72-97276934039a)

![2222222222](https://github.com/wukongdaily/tvhelper-docker/assets/143675923/e9ded16f-25ea-42e7-9035-37bb68fddd42)
