### ISSUE TITLE
Sony A95K 安装Disney+失败

### ISSUE THREAD

**Issue by MoMoZX** [wukongdaily/tvhelper-docker#20]
Sony A95K 安装Disney+失败，
报错APK安装失败:adb: failed to finalize session
Failure [INSTALL_FAILED_VERSION_DOWNGRADE]

**Comment by wukongdaily** [comment]
docker 镜像已更新。上传了新版迪士尼3.9.1-rc1-2024.11.07。你再试试吧。
要从新docker pull wukongdaily/box:v1.0.8

**Comment by MoMoZX** [comment]
感谢，已经可以了。
另外，可以添加一个HBO MAX。

**Comment by wukongdaily** [comment]
已经是了。目前HBOGO 就是HBO MAX。你直接安装HBOGO 即可。他们2个软件前几日宣布 二合一了
