### ISSUE TITLE
投影机可以安装吗？

### ISSUE THREAD

**Issue by xiabo4865041** [wukongdaily/tvhelper-docker#3]
悟空老师，我的是爱普生激光电视，腾讯极光系统，可以安装吗？

**Comment by wukongdaily** [comment]
使用脚本的条件：
1、电视、电视盒子、投影仪等任何运行了安卓的系统
2、能够打开ADB开关。有些盒子叫做 网络adb开关，有些盒子叫做USB调试开关。如何打开详见上期视频。https://youtu.be/_HENSyrvQRY?si=A1V_ncoXXqygpSaS&t=291
