### ISSUE TITLE
开发一个一键更换当贝桌面

### ISSUE THREAD

**Issue by winlion99** [wukongdaily/tvhelper-docker#4]
很多盒子刷机后很多桌面太乱了，不知道怎更换开机设置当贝桌面，这个有点难度，因为那些桌面都是内置,有root权限不一定能删除。可能有太多东西要处理才行。希望这个功能能实现。谢谢

**Comment by wukongdaily** [comment]
这个属于危险操作了。不过我会考虑的。一定不能卸载或者删除用户的程序，最多是禁用系统桌面。其实我做过一个手机版本的。

**Comment by wukongdaily** [comment]
https://github.com/wukongdaily/tvhelper-docker/releases/tag/v1.0.4
