### ISSUE TITLE
password 错误的

### ISSUE THREAD

**Issue by hongjinpan** [wukongdaily/tvhelper-docker#5]
使用 finalshell 无法登入，password出错

**Comment by wxrbbs** [comment]
我是威联通的，用docker-compose安装的，也碰到了这个问题无法ssh使用：/var/empty must be owned by root and not group or world-writable.  组权限问题，查了资料后找到解决方法如下：
运行代码重启就会解决
chown -R root:root /var/empty

**Comment by hongjinpan** [comment]
用内置的终端是可以打开的，就是用finalshell 无法登入，password出错 其怪。root的password我都是用拷进的，也不行.

**Comment by wukongdaily** [comment]
> 用内置的终端是可以打开的，就是用finalshell 无法登入，password出错 其怪。root的password我都是用拷进的，也不行.

请问你的宿主机也是威联通吗？

**Comment by hongjinpan** [comment]
宿主机是群晖

***@***.***
________________________________

**Comment by wukongdaily** [comment]
![1](https://github.com/wukongdaily/tvhelper-docker/assets/143675923/54486e52-258e-4bcf-b080-85223414ba9e)
我给你举例吧。

**Comment by wxrbbs** [comment]
> 用内置的终端是可以打开的，就是用finalshell 无法登入，password出错 其怪。root的password我都是用拷进的，也不行.

看日志错误有没有/var/empty must be owned by root and not group or world-writable错误
![屏幕截图 2024-03-08 120734](https://github.com/wukongdaily/tvhelper-docker/assets/11901616/3eb73a0d-16ed-4b6d-963f-85458073b76e)

如果有运行一下代码：
chown -R root：root /var/empty
