### ISSUE TITLE
感谢开发这么好用的工具

### ISSUE THREAD

**Issue by jjyjul** [wukongdaily/tvhelper-docker#9]
小米电视使用该应工具成功安装的 mytvsuper 和mix apps后 已成功安装 在小米自带的这用管理里看不见应用图标。在当贝里就可以看到，不知能否解决。(而我想安装当贝桌面来解决却系统又禁止安装)。而我另一台索尼电视全部正常

**Comment by wukongdaily** [comment]
安卓应用有2个图标，长图标和手机图标。长图标用于安卓原生TV，手机图标一般用于手机。<br>

其实Mix apps 是给安卓原生TV开发的，用来显示全部app。比如安卓原生TV默认无法显示手机版图标。安卓原生TV 使用了mix apps 后就能显示全部图标了。这是它的使用场景。而不是用于咱们国内定制的 非原生系统的。因为咱们的国产安卓系统本来就能显示手机版图标。这里要指出，sony电视的安卓系统，是比较特别，它的桌面兼容了长图标和手机图标的显示<br>

然后因为mix apps 这款应用本身，开发者只制作了长图标，没有制作手机版图标。因此在国产安卓系统显示不了，实则已经安装成功，仅仅是没显示图标而已。除非 小米电视安装了支持长图标的桌面，比如emotn ui 或者当贝桌面，那样你会发现mix apps 就出现了。mytvsuper 也是如此。<br>

综上，安卓电视机顶盒图标问题是一个老生常谈的问题，谷歌没有强制要求开发者必须制作2个图标，因此会出现参差不齐的情况，也许谷歌的意图是希望应用有倾向性，andorid tv 和 android 手机分开。

**Comment by jjyjul** [comment]
谢谢解答。无想到科技发展，我和大神的距离拉近了。那目前我只想办法安装 emotn ui 或者当贝桌面了 今晚回去用adb安装试下能绕过限制
